site_name: Documentation

theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material

extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css

plugins:
  - search
  - macros
  - monorepo

extra:
  version_maj: 20
  version_majmin: 20.0
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - image_captions:
      numbering: true
  - table_captions:
      numbering: true
      caption_top: false
  - caption
  - toc:
      title: On this page

nav:
  - Release Notes V19.0: "!include ./release-notes-v19-0/mkdocs.yml"
  - Windows Installation: "!include ./windows-installation-and-configuration-guide/mkdocs.yml"
  - UNIX Installation: "!include ./unix-installation-and-configuration-guide/mkdocs.yml"
  - Programmer's Guide: "!include ./programming-reference-guide/mkdocs.yml"
  - Language Reference: "!include ./language-reference-guide/mkdocs.yml"
  - Object Reference: "!include ./object-reference/mkdocs.yml"
  - Windows UI Guide: "!include ./windows-ui-guide/mkdocs.yml"
  - Interface Guide: "!include ./interface-guide/mkdocs.yml"
  - .NET Interface: "!include ./dotnet-interface/mkdocs.yml"
  - UNIX User Guide: "!include ./unix-user-guide/mkdocs.yml"
  




