site_name: Documentation
repo_url: https://github.com/dyalog/documentation
copyright: Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener"><strong>Material for MkDocs</strong></a><br/>Copyright &copy; 1982-$CURRENT_YEAR <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog, LTD</a></strong> ($BUILD_DATE $GIT_INFO)


theme:
  favicon: 'img/favicon-32.png'
  logo: img/dyalog-logo-2025_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
      text: Be Vietnam Pro

extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
  -
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - privacy
  - search
  - macros
  - monorepo
  - caption:
      table: 
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom

extra:
  version_maj: 20
  version_majmin: 20.0
  version:
    provider: mike
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page

nav:
  - Release Notes V19.0: "!include ./release-notes-v19-0/mkdocs.yml"
  - Windows Installation: "!include ./windows-installation-and-configuration-guide/mkdocs.yml"
  - UNIX Installation: "!include ./unix-installation-and-configuration-guide/mkdocs.yml"
  - Programmer's Guide: "!include ./programming-reference-guide/mkdocs.yml"
  - Language Reference: "!include ./language-reference-guide/mkdocs.yml"
  - Object Reference: "!include ./object-reference/mkdocs.yml"
  - Windows UI Guide: "!include ./windows-ui-guide/mkdocs.yml"
  - Interface Guide: "!include ./interface-guide/mkdocs.yml"
  - .NET Interface: "!include ./dotnet-interface/mkdocs.yml"
  - UNIX User Guide: "!include ./unix-user-guide/mkdocs.yml"
  - Licences for third-party components: licences-overview.md
  - Trademarks: trademarks.md
  




