site_name: UNIX User Guide
theme:
  favicon: img/favicon-32.png
  logo: img/dyalog-logo-2025_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Introduction:
    - Overview: overview.md
    - Entering Characters: entering-characters.md
    - Entering Nest and Stencil Characters: entering-the-stencil-character.md
    - Entering Commands: entering-commands.md
  - Input Windows: the-different-input-windows.md
  - Driving the tty version: driving-tty-dyalog-apl.md
  - Starting APL: starting-apl.md
  - Configuring the Editor: configuring-the-editor.md
  - File Permissions and FSTAC: file-permissions-and-fstac.md
  - Calling UNIXÂ Commands: calling-unix-commands.md
  - Signals and Trap: signals-and-trap.md
  - BuildID: buildid.md
  - Core and APLCore Files: core-and-aplcore-files.md
  - Appendix A: appendix-a-table-of-keycodes-te.md
  - Appendix B: appendix-b-table-of-keycodes-putty.md
  - Appendix C: appendix-c-unused-keycodes.md
