site_name: Windows Installation and Configuration Guide
theme:
  favicon: img/favicon-32.png
  logo: img/dyalog-white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Documentation: documentation.md
  - Files and Directories: files-and-directories.md
  - File Extensions: file-associations.md
  - APL Fonts: apl-fonts.md
  - Interoperability and Compatibility: interoperability.md
  - The APL Command Line: apl-command-line.md
  - APL Exit Codes: apl-exit-codes.md
  - Dyalog Serial Number: dyalog-serial-number.md
  - Configuration Parameters:
      - Introduction: configuration-parameters/configuration-parameters.md
      - AddClassHeaders: configuration-parameters/addclassheaders.md
      - AplCoreName: configuration-parameters/aplcorename.md
      - aplk: configuration-parameters/aplk.md
      - aplkeys: configuration-parameters/aplkeys.md
      - aplnid: configuration-parameters/aplnid.md
      - aplt: configuration-parameters/aplt.md
      - apltrans: configuration-parameters/apltrans.md
      - APL_CODE_E_MAGNITUDE: configuration-parameters/apl-code-e-magnitude.md
      - APL_COMPLEX_AS_V12: configuration-parameters/apl-complex-as-v12.md
      - APL_FCREATE_PROPS_C: configuration-parameters/apl-fcreate-props-c.md
      - APL_FCREATE_PROPS_J: configuration-parameters/apl-fcreate-props-j.md
      - APL_FAST_FCHK: configuration-parameters/apl-fast-fchk.md
      - APL_MAX_THREADS: configuration-parameters/apl-max-threads.md
      - APL_TextInAplCore: configuration-parameters/apl-textinaplcore.md
      - AutoDPI: configuration-parameters/autodpi.md
      - AutoComplete:
          - CancelKey1: configuration-parameters/autocomplete/cancelkey1.md
          - CancelKey2: configuration-parameters/autocomplete/cancelkey2.md
          - Cols: configuration-parameters/autocomplete/cols.md
          - CommonKey1: configuration-parameters/autocomplete/commonkey1.md
          - CompleteKey1: configuration-parameters/autocomplete/completekey1.md
          - CompleteKey2: configuration-parameters/autocomplete/completekey2.md
          - Enabled: configuration-parameters/autocomplete/enabled.md
          - History: configuration-parameters/autocomplete/history.md
          - HistorySize: configuration-parameters/autocomplete/historysize.md
          - PrefixSize: configuration-parameters/autocomplete/prefixsize.md
          - Rows: configuration-parameters/autocomplete/rows.md
          - ShowFiles: configuration-parameters/autocomplete/showfiles.md
      - AutoFormat: configuration-parameters/autoformat.md
      - AutoIndent: configuration-parameters/autoindent.md
      - auto_pw: configuration-parameters/auto-pw.md
      - CFEXT: configuration-parameters/cfext.md
      - ClassicMode: configuration-parameters/classicmode.md
      - ClassicModeSavePosition: configuration-parameters/classicmodesaveposition.md
      - CMD_PREFIX and CMD_POSTFIX: configuration-parameters/cmd-prefix-and-cmd-postfix.md
      - ConfigFile: configuration-parameters/configfile.md
      - confirm_abort: configuration-parameters/confirm-abort.md
      - confirm_close: configuration-parameters/confirm-close.md
      - confirm_fix: configuration-parameters/confirm-fix.md
      - confirm_session_delete: configuration-parameters/confirm-session-delete.md
      - default_div: configuration-parameters/default-div.md
      - default_io: configuration-parameters/default-io.md
      - default_ml: configuration-parameters/default-ml.md
      - default_pp: configuration-parameters/default-pp.md
      - default_pw: configuration-parameters/default-pw.md
      - default_rtl: configuration-parameters/default-rtl.md
      - default_wx: configuration-parameters/default-wx.md
      - DMXOUTPUTONERROR: configuration-parameters/dmxoutputonerror.md
      - DockableEditWindows: configuration-parameters/dockableeditwindows.md
      - DoubleClickEdit: configuration-parameters/doubleclickedit.md
      - dyalog: configuration-parameters/dyalog.md
      - DyalogEmailAddress: configuration-parameters/dyalogemailaddress.md
      - DyalogHelpDir: configuration-parameters/dyaloghelpdir.md
      - DyalogInstallDir: configuration-parameters/dyaloginstalldir.md
      - DyalogLink: configuration-parameters/dyaloglink.md
      - DyalogStartup: configuration-parameters/dyalogstartup.md
      - DyalogStartupSE: configuration-parameters/dyalogstartupse.md
      - DyalogStartup_X: configuration-parameters/dyalogstartup-x.md
      - DyalogWebSite: configuration-parameters/dyalogwebsite.md
      - DYALOG_DISCARD_FN_SOURCE: configuration-parameters/dyalog-discard-fn-source.md
      - DYALOG_EVENTLOGGINGLEVEL: configuration-parameters/dyalog-eventlogginglevel.md
      - DYALOG_EVENTLOGNAME: configuration-parameters/dyalog-eventlogname.md
      - DYALOG_GUTTER_ENABLE: configuration-parameters/dyalog-gutter-enable.md
      - Dyalog_LineEditor_Mode: configuration-parameters/dyalog-lineeditor-mode.md
      - Dyalog_NETCore: configuration-parameters/dyalog-netcore.md
      - DYALOG_NOPOPUPS: configuration-parameters/dyalog-nopopups.md
      - DYALOG_PIXEL_TYPE: configuration-parameters/dyalog-pixel-type.md
      - DYALOG_SERIAL: configuration-parameters/dyalog-serial.md
      - EditorState: configuration-parameters/editorstate.md
      - Edit_Cols: configuration-parameters/edit-cols.md
      - Edit_First_X: configuration-parameters/edit-first-x.md
      - Edit_First_Y: configuration-parameters/edit-first-y.md
      - Edit_Offset_X: configuration-parameters/edit-offset-x.md
      - Edit_Offset_Y: configuration-parameters/edit-offset-y.md
      - Edit_Rows: configuration-parameters/edit-rows.md
      - ENABLE_CEF: configuration-parameters/enable-cef.md
      - ErrorOnExternalException: configuration-parameters/erroronexternalexception.md
      - ExternalHelpURL: configuration-parameters/externalhelpurl.md
      - File_Stack_Size: configuration-parameters/file-stack-size.md
      - greet_bitmap: configuration-parameters/greet-bitmap.md
      - history_size: configuration-parameters/history-size.md
      - inifile: configuration-parameters/inifile.md
      - InitFullScriptNormal: configuration-parameters/initfullscriptnormal.md
      - InitFullScriptSusp: configuration-parameters/initfullscriptsusp.md
      - InitialKeyboardLayout: configuration-parameters/initialkeyboardlayout.md
      - InitialKeyboardLayoutInUse: configuration-parameters/initialkeyboardlayoutinuse.md
      - InitialKeyboardLayoutShowAll: configuration-parameters/initialkeyboardlayoutshowall.md
      - input_size: configuration-parameters/input-size.md
      - KeyboardInputDelay: configuration-parameters/keyboardinputdelay.md
      - Load: configuration-parameters/load.md
      - localdyalogdir: configuration-parameters/localdyalogdir.md
      - log_file: configuration-parameters/log-file.md
      - log_file_inuse: configuration-parameters/log-file-inuse.md
      - log_size: configuration-parameters/log-size.md
      - LX: configuration-parameters/lx.md
      - mapchars: configuration-parameters/mapchars.md
      - MaxAplCores: configuration-parameters/maxaplcores.md
      - maxws: configuration-parameters/maxws.md
      - OverstrikesPopup: configuration-parameters/overstrikespopup.md
      - PassExceptionsToOpSys: configuration-parameters/passexceptionstoopsys.md
      - pfkey_size: configuration-parameters/pfkey-size.md
      - ProgramFolder: configuration-parameters/programfolder.md
      - PropertyExposeRoot: configuration-parameters/propertyexposeroot.md
      - PropertyExposeSE: configuration-parameters/propertyexposese.md
      - qcmd_timeout: configuration-parameters/qcmd-timeout.md
      - ResolveOverstrikes: configuration-parameters/resolveoverstrikes.md
      - RIDE_Init: configuration-parameters/ride-init.md
      - RIDE_Spawned: configuration-parameters/ride-spawned.md
      - RunAsService: configuration-parameters/runasservice.md
      - SaveContinueOnExit: configuration-parameters/savecontinueonexit.md
      - SaveLogOnExit: configuration-parameters/savelogonexit.md
      - SaveSessionOnExit: configuration-parameters/savesessiononexit.md
      - Serial: configuration-parameters/serial.md
      - SessionOnTop: configuration-parameters/sessionontop.md
      - session_file: configuration-parameters/session-file.md
      - ShowStatusOnError: configuration-parameters/showstatusonerror.md
      - SingleTrace: configuration-parameters/singletrace.md
      - SkipLines: configuration-parameters/skiplines.md
      - SM_Cols: configuration-parameters/sm-cols.md
      - SM_Rows: configuration-parameters/sm-rows.md
      - StatusOnEdit: configuration-parameters/statusonedit.md
      - TabStops: configuration-parameters/tabstops.md
      - ToolBarsOnEdit: configuration-parameters/toolbarsonedit.md
      - TraceStopMonitor: configuration-parameters/tracestopmonitor.md
      - Trace_First_X: configuration-parameters/trace-first-x.md
      - Trace_First_Y: configuration-parameters/trace-first-y.md
      - Trace_level_warn: configuration-parameters/trace-level-warn.md
      - Trace_Offset_X: configuration-parameters/trace-offset-x.md
      - Trace_Offset_Y: configuration-parameters/trace-offset-y.md
      - Trace_On_Error: configuration-parameters/trace-on-error.md
      - UCMDCacheFile: configuration-parameters/ucmdcachefile.md
      - UnicodeToClipboard: configuration-parameters/unicodetoclipboard.md
      - URLHighlight: configuration-parameters/urlhighlight.md
      - UseExternalHelpURL: configuration-parameters/useexternalhelpurl.md
      - UserConfigFile: configuration-parameters/userconfigfile.md
      - UseXCV: configuration-parameters/usexcv.md
      - ValueTips:
          - ValueTips/ColourScheme: configuration-parameters/valuetips/colourscheme.md
          - ValueTips/Delay: configuration-parameters/valuetips/delay.md
          - ValueTips/Enabled: configuration-parameters/valuetips/enabled.md
      - WantsSpecialKeys: configuration-parameters/wantsspecialkeys.md
      - WrapSearch: configuration-parameters/wrapsearch.md
      - WrapSearchMsgBox: configuration-parameters/wrapsearchmsgbox.md
      - WSEXT: configuration-parameters/wsext.md
      - WSPATH: configuration-parameters/wspath.md
      - XPLookAndFeel: configuration-parameters/xplookandfeel.md
      - yy_window: configuration-parameters/yy-window.md
  - Registry SubFolders: registry-subfolders.md
  - Configuration Files: configuration-files.md
  - Window Captions: window-captions.md
  - Workspace Management: workspace-management.md
  - Interface with Windows: interface-with-windows.md
  - Auxiliary Processors: auxiliary-processors.md
  - Access Control for External Variables: access-control-for-external-variables.md
  - Shell Scripts: shell-scripts.md
  - Creating Executables: creating-executables.md
  - Run-Time Applications and Components: runtime-applications-and-components.md
  - Run-Time Applications Additonal Considerations: runtime-applications-addional.md
  - COM Objects and the Dyalog APL DLL: com-objects-and-the-dyalog-dll.md
  - APL Application as a Service: apl-application-as-a-service.md
  - APLService Logging Events: aplservice-logging-events.md
  - Configuring the IDE:
      - Configuration Dialog:
          - General Tab: configuring-the-ide/configuration-dialog/configuration-dialog-general-tab.md
          - Unicode Input Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-unicode-input-tab-unicode-edition-only.md
          - Input Tab (Classic Edition): 
              configuring-the-ide/configuration-dialog/configuration-dialog-input-tab-classic-edition-only.md
          - Output Tab (Classic Edition): 
              configuring-the-ide/configuration-dialog/configuration-dialog-output-tab-classic-edition-only.md
          - Keyboard Shortcuts Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-keyboard-shortcuts-tab.md
          - Workspace Tab: configuring-the-ide/configuration-dialog/configuration-dialog-workspace-tab.md
          - Help/DMX Tab: configuring-the-ide/configuration-dialog/configuration-dialog-help-dmx-tab.md
          - Windows Tab: configuring-the-ide/configuration-dialog/configuration-dialog-windows-tab.md
          - Session Tab: configuring-the-ide/configuration-dialog/configuration-dialog-session-tab.md
          - Trace/Edit Tab: configuring-the-ide/configuration-dialog/configuration-dialog-trace-edit-tab.md
          - Auto Complete Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-auto-complete-tab.md
          - SALT Tab: configuring-the-ide/configuration-dialog/configuration-dialog-salt-tab.md
          - User Commands Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-user-commands-tab.md
          - Object Syntax Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-object-syntax-tab.md
          - Saved ResponsesTab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-saved-responsestab.md
      - Colour Selection Dialog: configuring-the-ide/colour-selection-dialog.md
      - Print Configuration Dialog: configuring-the-ide/print-configuration.md
