site_name: Windows UI Guide
theme:
  favicon: img/favicon-32.png
  logo: img/dyalog-white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Introduction: introduction.md
  - APL Keyboards: apl-keyboards.md
  - Session Manager: session-manager.md
  - Session Gutter: session-gutter.md
  - Multi-line Session Input: multiline-session-input.md
  - Unicode Edition Keyboard: unicode-edition-keyboard.md
  - IME Configuration: ime-configuration.md
  - Classic Edition Keyboard: classic-edition-keyboard.md
  - Keyboard Shortcuts: keyboard-shortcuts.md
  - Session Colour Scheme: session-colour-scheme.md
  - The Session Window: the-session-window.md
  - Language Bar: language-bar.md
  - Entering and Executing Expressions: entering-and-executing-expressions.md
  - Value Tips: value-tips.md
  - Value Tips for External Functions: value-tips-external.md
  - Configuring Value Tips: value-tips-configuring.md
  - Array Editor: array-editor.md
  - Session GUI: session-gui.md
  - Session MenuBar: session-menubar.md
  - Session Popup Menu: session-popup-menu.md
  - The Session Toolbars: session-toolbars.md
  - Session StatusBar: session-statusbar.md
  - Status Window: status-window.md
  - Workspace Explorer: workspace-explorer.md
  - Browsing Classes: browsing-classes.md
  - Browsing Type Libraries: browsing-type-libraries.md
  - Browsing .Net Classes: browsing-net-classes.md
  - Find Objects Tool: find-objects-tool.md
  - Object Properties Dialog: object-properties-dialog.md
  - Editor: editor.md
  - Find and Replace Dialogs: find-and-replace-dialogs.md
  - Editing Scripts and Text Files: editing-scripts-and-text-files.md
  - Source as Typed: source-as-typed.md
  - The Tracer: 
      - tracer/index.md
      - Trace Primitives: tracer/trace-primitives.md
  - The Threads Tool: threads-tool.md
  - Debugging Threads: debugging-threads.md
  - The Event Viewer: event-viewer.md
  - The Session Object:
      - Introduction: the-session-object/session-object.md
      - AfterFix: the-session-object/afterfix.md
      - Fix: the-session-object/fix.md
      - Format: the-session-object/format.md
      - SessionPrint Event: the-session-object/sessionprint.md
      - SessionTrace: the-session-object/sessiontrace.md
      - WorkspaceLoaded Event: the-session-object/workspaceloaded.md
      - Configuring the Session: the-session-object/configuring-the-session.md
      - Session Initialisation: the-session-object/session-initialisation.md
  - User Commands: user-commands.md
  - File Explorer Integration: file-explorer-integration.md
