
site_name: .NET Framework Interface Guide
theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material

extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css

plugins:
  - search
  - macros
  - site-urls

extra:
  version_maj: 20
  version_majmin: 20.0

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - image_captions:
      numbering: true
  - table_captions:
      numbering: true
      caption_top: false
  - caption
  - toc:
      title: On this page

nav:
  
  - Overview:
    -  Introduction: overview/introduction.md
    -  Prerequisites: overview/prerequisites.md
    -  Files Installed with Dyalog: overview/files-installed-with-dyalog.md
  - Accessing .Net Classes:
    -  Introduction: accessing-net-classes/introduction.md
    -  Locating .NET Classes and Assemblies: accessing-net-classes/locating-net-classes-and-assemblies.md
    -  Using .NET Classes: accessing-net-classes/using-net-classes.md
    -  Browsing .NET Classes: accessing-net-classes/browsing-net-classes.md
    -  Value Tips for External Functions: accessing-net-classes/value-tips-external.md
    -  Advanced Techniques: accessing-net-classes/advanced-techniques.md
    -  More Examples: accessing-net-classes/more-examples.md
    -  Enumerations: accessing-net-classes/enumerations.md
    -  Handling Pointers with Dyalog.ByRef: accessing-net-classes/handling-pointers-with-dyalog.md
    -  DECF Conversion: accessing-net-classes/decf-conversions.md
  - Using Windows.Forms:
    -  Introduction: using-windows-forms/introduction.md
    -  Creating GUI Objects: using-windows-forms/creating-gui-objects.md
    -  Object Hierarchy: using-windows-forms/object-hierarchy.md
    -  Positioning and Sizing Forms and Controls: using-windows-forms/positioning-and-sizing-forms.md
    -  Modal Dialog Boxes: using-windows-forms/modal-dialog-boxes.md
    -  Non-Modal Forms: using-windows-forms/non-modal-forms.md
  - WPF:
    -  Introduction: wpf/introduction.md
    - Temperature Converter:
      -  Temperature Converter Tutorial: wpf/temperature-converter/temperature-converter-intro.md
      -  Using XAML: wpf/temperature-converter/using-xaml.md
      -  Using Code: wpf/temperature-converter/using-code.md
    - Data Binding:
      - wpf/data-binding/data-binding-introduction.md
      -  Example 1: wpf/data-binding/text-example.md
      -  Example 2: wpf/data-binding/fontsize-example.md
      -  Example 3: wpf/data-binding/text-and-fontsize-code.md
      -  Example 4: wpf/data-binding/text-and-fontsize-xaml.md
      -  Example 5: wpf/data-binding/filtered-list.md
      -  Example 6: wpf/data-binding/netobject-example.md
      -  Example 6a (Casting to DateTime): wpf/data-binding/datetime-example-using-ts-format.md
      -  Example 7: wpf/data-binding/datagrid-example.md
      -  Example 8: wpf/data-binding/datagrid-matrix-example.md
    -  Syncfusion Libraries: wpf/syncfusion-introduction.md
    -  Syncfusion Circular Gauge Example: wpf/syncfusion-circulargauge.md
  - APLScript:
    -  Introduction: aplscript/introduction.md
    -  The APLScript Compiler: aplscript/aplscript-compiler.md
    -  Creating an APLScript File: aplscript/creating-an-aplscript-file.md
    -  Copying code from the Dyalog  Session: aplscript/transferring-code.md
    -  General principles of APLScript: aplscript/general-principles.md
    -  Creating Programs (.exe) with APLScript: aplscript/creating-programs.md
    -  Creating .NET Classes with APLScript: aplscript/creating-net-classes.md
    -  Creating ASP.NET Classes with APLScript: aplscript/creating-asp-net-classes.md
  - Writing .Net Classes:
    -  Introduction: writing-net-classes/introduction.md
    -  Assemblies, Namespaces and Classes: writing-net-classes/assemblies-namespaces-and-classes.md
    -  Getting Started: writing-net-classes/getting-started.md
    -  Example 1: writing-net-classes/aplclasses1.md
    -  Example 2: writing-net-classes/aplclasses2.md
    -  Example 2a: writing-net-classes/aplclasses2a.md
    -  Example 3: writing-net-classes/aplclasses3.md
    -  Example 4: writing-net-classes/aplclasses4.md
    -  Example 5: writing-net-classes/aplclasses5.md
    -  Interfaces: writing-net-classes/interfaces.md
  - Dyalog APL and IIS:
    -  Introduction: dyalog-apl-and-iis/introduction.md
    -  IIS Installation Dependency: dyalog-apl-and-iis/iis-installation-dependency.md
    -  IIS Applications, Virtual Directories, Application Pools: dyalog-apl-and-iis/iis-applications-and-virtual.md
    -  Internet Services Manager: dyalog-apl-and-iis/internet-services-manager.md
  - Writing Web Services:
    -  Introduction: writing-web-services/introduction.md
    -  Web Service (.asmx) Scripts: writing-web-services/web-service-asmx-scripts.md
    -  Compilation: writing-web-services/compilation.md
    -  Exporting Methods: writing-web-services/exporting-methods.md
    -  Web Service Data Types: writing-web-services/web-service-data-types.md
    -  Execution: writing-web-services/execution.md
    -  Global.asax, Application and Session Objects: writing-web-services/global-asax-and-application.md
    - " Sample Web Service: EG1": writing-web-services/sample-web-service-eg1.md
    - " Sample Web Service: LoanService": writing-web-services/sample-web-service-loanservice.md
    - " Sample Web Service: GolfService": writing-web-services/sample-web-service-golfservice.md
    - " Sample Web Service: EG2": writing-web-services/sample-web-service-eg2.md
  - Calling Web Services:
    -  Introduction: calling-web-services/introduction.md
    -  The MakeProxy function: calling-web-services/makeproxy-function.md
    -  Using LoanService from Dyalog APL: calling-web-services/using-loanservice-from-dyalog.md
    -  Using GolfService from Dyalog APL: calling-web-services/using-golfservice-from-dyalog.md
    -  Exploring Web Services: calling-web-services/exploring-web-services.md
    -  Asynchronous Use: calling-web-services/asynchronous-use.md
  - Writing ASP.NET Web pages:
    -  Introduction: writing-asp-net-web-pages/introduction.md
    -  Your first APL Web Page: writing-asp-net-web-pages/your-first-apl-web-page.md
    -  The Page_Load Event: writing-asp-net-web-pages/page-load-event.md
    -  Code Behind: writing-asp-net-web-pages/code-behind.md
    -  Workspace Behind: writing-asp-net-web-pages/workspace-behind.md
  - Writing Custom Controls for ASP.NET:
    -  Introduction: writing-custom-controls-for-asp-net/introduction.md
    -  The SimpleCtl Control: writing-custom-controls-for-asp-net/simplectl-control.md
    -  The TemperatureConverterCtl1 Control: writing-custom-controls-for-asp-net/temperatureconverterctl1.md
    -  The TemperatureConverterCtl2 Control: writing-custom-controls-for-asp-net/temperatureconverterctl2.md
    -  The TemperatureConverterCtl3 Control: writing-custom-controls-for-asp-net/temperatureconverterctl3.md
  - Implementation Details:
    -  Introduction: implementation-details/introduction.md
    -  Isolation Mode: implementation-details/isolation-mode.md
    -  Workspace Size: implementation-details/workspace-size.md
    -  Structure of the Active Workspace: implementation-details/structure-of-the-active-workspace.md
    -  Threading: implementation-details/threading.md
    -  Debugging an APL.NET Class: implementation-details/debugging-an-apl-net-class.md
    -  The web.config file: implementation-details/asp-net-configuration-file.md
