site_name: UNIX Installation and Configuration Guide
theme:
  favicon: img/favicon-32.png
  logo: img/dyalog-logo-2025_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Installation:
    - introduction.md
    - installation.md
  - Dyalog Serial Number: dyalog-serial-number.md
  - Konsole: linux-console-config.md
  - APL VNC RDP: apl-vnc-rdp.md
  - PuTTY: putty.md
  - Configuration Parameters:
      - Introduction: configuration-parameters/configuration-parameters.md
      - Configuration Files: configuration-parameters/configuration-files.md
      - Environment Variables: configuration-parameters/environment-variables.md
  - Configuring the Editor: configuring-the-editor.md
  - Starting from scripts: starting-apl-from-scripts.md
  - Magic: magic.md
  - SE and SALT: se-and-user-commands.md
  - HOME dyalog directory: home-dyalog-directory.md
  - QuadNA and UNIX: quadna.md
  - Miscellaneous: miscellaneous.md
  - BuildID: buildid.md
